/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2' in SOPC Builder design 'nios'
 * SOPC Builder design path: ../nios.sopcinfo
 *
 * Generated: Thu Jun 27 09:23:41 JST 2019
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00000020
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x18
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00800020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x18
#define ALT_CPU_NAME "nios2_gen2"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00002000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00000020
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x18
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00800020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x18
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00002000


/*
 * DEBport configuration
 *
 */

#define ALT_MODULE_CLASS_DEBport altera_avalon_pio
#define DEBPORT_BASE 0x1050
#define DEBPORT_BIT_CLEARING_EDGE_REGISTER 0
#define DEBPORT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DEBPORT_CAPTURE 0
#define DEBPORT_DATA_WIDTH 8
#define DEBPORT_DO_TEST_BENCH_WIRING 0
#define DEBPORT_DRIVEN_SIM_VALUE 0
#define DEBPORT_EDGE_TYPE "NONE"
#define DEBPORT_FREQ 50000000
#define DEBPORT_HAS_IN 0
#define DEBPORT_HAS_OUT 1
#define DEBPORT_HAS_TRI 0
#define DEBPORT_IRQ -1
#define DEBPORT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DEBPORT_IRQ_TYPE "NONE"
#define DEBPORT_NAME "/dev/DEBport"
#define DEBPORT_RESET_VALUE 0
#define DEBPORT_SPAN 16
#define DEBPORT_TYPE "altera_avalon_pio"


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_ONCHIP_FLASH
#define __AV_SL
#define __BEMICRO_MAX10_SERIAL_FLASH_CONTROLLER
#define __FT245IF2
#define __ILI9341_SPI16


/*
 * ILI9341SPI configuration
 *
 */

#define ALT_MODULE_CLASS_ILI9341SPI ili9341_spi16
#define ILI9341SPI_BASE 0x3800
#define ILI9341SPI_IRQ -1
#define ILI9341SPI_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ILI9341SPI_NAME "/dev/ILI9341SPI"
#define ILI9341SPI_SPAN 16
#define ILI9341SPI_TYPE "ili9341_spi16"


/*
 * ILI9341SPI configuration as viewed by dma_LCD_write_master
 *
 */

#define DMA_LCD_WRITE_MASTER_ILI9341SPI_BASE 0x3800
#define DMA_LCD_WRITE_MASTER_ILI9341SPI_IRQ -1
#define DMA_LCD_WRITE_MASTER_ILI9341SPI_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_LCD_WRITE_MASTER_ILI9341SPI_NAME "/dev/ILI9341SPI"
#define DMA_LCD_WRITE_MASTER_ILI9341SPI_SPAN 16
#define DMA_LCD_WRITE_MASTER_ILI9341SPI_TYPE "ili9341_spi16"


/*
 * LED configuration
 *
 */

#define ALT_MODULE_CLASS_LED altera_avalon_pio
#define LED_BASE 0x1060
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 8
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE "NONE"
#define LED_FREQ 50000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ -1
#define LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LED_IRQ_TYPE "NONE"
#define LED_NAME "/dev/LED"
#define LED_RESET_VALUE 0
#define LED_SPAN 16
#define LED_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x1100
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x1100
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x1100
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios"


/*
 * button configuration
 *
 */

#define ALT_MODULE_CLASS_button altera_avalon_pio
#define BUTTON_BASE 0x1040
#define BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_CAPTURE 0
#define BUTTON_DATA_WIDTH 4
#define BUTTON_DO_TEST_BENCH_WIRING 0
#define BUTTON_DRIVEN_SIM_VALUE 0
#define BUTTON_EDGE_TYPE "NONE"
#define BUTTON_FREQ 50000000
#define BUTTON_HAS_IN 1
#define BUTTON_HAS_OUT 0
#define BUTTON_HAS_TRI 0
#define BUTTON_IRQ -1
#define BUTTON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BUTTON_IRQ_TYPE "NONE"
#define BUTTON_NAME "/dev/button"
#define BUTTON_RESET_VALUE 0
#define BUTTON_SPAN 16
#define BUTTON_TYPE "altera_avalon_pio"


/*
 * dma configuration
 *
 */

#define ALT_MODULE_CLASS_dma altera_avalon_dma
#define DMA_ALLOW_BYTE_TRANSACTIONS 1
#define DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 1
#define DMA_ALLOW_HW_TRANSACTIONS 1
#define DMA_ALLOW_QUADWORD_TRANSACTIONS 1
#define DMA_ALLOW_WORD_TRANSACTIONS 1
#define DMA_BASE 0x1080
#define DMA_IRQ 4
#define DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_LENGTHWIDTH 16
#define DMA_MAX_BURST_SIZE 128
#define DMA_NAME "/dev/dma"
#define DMA_SPAN 32
#define DMA_TYPE "altera_avalon_dma"


/*
 * dma_LCD configuration
 *
 */

#define ALT_MODULE_CLASS_dma_LCD altera_avalon_dma
#define DMA_LCD_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_LCD_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_LCD_ALLOW_HW_TRANSACTIONS 1
#define DMA_LCD_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_LCD_ALLOW_WORD_TRANSACTIONS 0
#define DMA_LCD_BASE 0x10a0
#define DMA_LCD_IRQ 3
#define DMA_LCD_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_LCD_LENGTHWIDTH 18
#define DMA_LCD_MAX_BURST_SIZE 128
#define DMA_LCD_NAME "/dev/dma_LCD"
#define DMA_LCD_SPAN 32
#define DMA_LCD_TYPE "altera_avalon_dma"


/*
 * ft245 configuration
 *
 */

#define ALT_MODULE_CLASS_ft245 ft245if2
#define FT245_BASE 0x3000
#define FT245_IRQ 6
#define FT245_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FT245_NAME "/dev/ft245"
#define FT245_SPAN 32
#define FT245_TYPE "ft245if2"


/*
 * ft245 configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_FT245_BASE 0x3000
#define DMA_READ_MASTER_FT245_IRQ -1
#define DMA_READ_MASTER_FT245_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_FT245_NAME "/dev/ft245"
#define DMA_READ_MASTER_FT245_SPAN 32
#define DMA_READ_MASTER_FT245_TYPE "ft245if2"


/*
 * ft245 configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_FT245_BASE 0x3000
#define DMA_WRITE_MASTER_FT245_IRQ -1
#define DMA_WRITE_MASTER_FT245_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_FT245_NAME "/dev/ft245"
#define DMA_WRITE_MASTER_FT245_SPAN 32
#define DMA_WRITE_MASTER_FT245_TYPE "ft245if2"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK SYS_CLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x1100
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * onchip_flash configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_flash altera_onchip_flash
#define ONCHIP_FLASH_BASE 0x80000
#define ONCHIP_FLASH_BYTES_PER_PAGE 2048
#define ONCHIP_FLASH_IRQ -1
#define ONCHIP_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_FLASH_NAME "/dev/onchip_flash"
#define ONCHIP_FLASH_READ_ONLY_MODE 0
#define ONCHIP_FLASH_SECTOR1_ENABLED 1
#define ONCHIP_FLASH_SECTOR1_END_ADDR 0x3fff
#define ONCHIP_FLASH_SECTOR1_START_ADDR 0
#define ONCHIP_FLASH_SECTOR2_ENABLED 1
#define ONCHIP_FLASH_SECTOR2_END_ADDR 0x7fff
#define ONCHIP_FLASH_SECTOR2_START_ADDR 0x4000
#define ONCHIP_FLASH_SECTOR3_ENABLED 0
#define ONCHIP_FLASH_SECTOR3_END_ADDR 0xffffffff
#define ONCHIP_FLASH_SECTOR3_START_ADDR 0xffffffff
#define ONCHIP_FLASH_SECTOR4_ENABLED 0
#define ONCHIP_FLASH_SECTOR4_END_ADDR 0xffffffff
#define ONCHIP_FLASH_SECTOR4_START_ADDR 0xffffffff
#define ONCHIP_FLASH_SECTOR5_ENABLED 0
#define ONCHIP_FLASH_SECTOR5_END_ADDR 0xffffffff
#define ONCHIP_FLASH_SECTOR5_START_ADDR 0xffffffff
#define ONCHIP_FLASH_SPAN 32768
#define ONCHIP_FLASH_TYPE "altera_onchip_flash"


/*
 * pdm configuration
 *
 */

#define ALT_MODULE_CLASS_pdm av_sl
#define PDM_BASE 0x4000
#define PDM_IRQ -1
#define PDM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PDM_NAME "/dev/pdm"
#define PDM_SPAN 4096
#define PDM_TYPE "av_sl"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x800000
#define SDRAM_CAS_LATENCY 2
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 15.625
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x16
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 8
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 12
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 8388608
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.4
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 15.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 15.0
#define SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by dma_LCD_read_master
 *
 */

#define DMA_LCD_READ_MASTER_SDRAM_BASE 0x800000
#define DMA_LCD_READ_MASTER_SDRAM_CAS_LATENCY 2
#define DMA_LCD_READ_MASTER_SDRAM_CONTENTS_INFO
#define DMA_LCD_READ_MASTER_SDRAM_INIT_NOP_DELAY 0.0
#define DMA_LCD_READ_MASTER_SDRAM_INIT_REFRESH_COMMANDS 2
#define DMA_LCD_READ_MASTER_SDRAM_IRQ -1
#define DMA_LCD_READ_MASTER_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_LCD_READ_MASTER_SDRAM_IS_INITIALIZED 1
#define DMA_LCD_READ_MASTER_SDRAM_NAME "/dev/sdram"
#define DMA_LCD_READ_MASTER_SDRAM_POWERUP_DELAY 100.0
#define DMA_LCD_READ_MASTER_SDRAM_REFRESH_PERIOD 15.625
#define DMA_LCD_READ_MASTER_SDRAM_REGISTER_DATA_IN 1
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_ADDR_WIDTH 0x16
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_BANK_WIDTH 2
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_COL_WIDTH 8
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_DATA_WIDTH 16
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_NUM_BANKS 4
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define DMA_LCD_READ_MASTER_SDRAM_SDRAM_ROW_WIDTH 12
#define DMA_LCD_READ_MASTER_SDRAM_SHARED_DATA 0
#define DMA_LCD_READ_MASTER_SDRAM_SIM_MODEL_BASE 0
#define DMA_LCD_READ_MASTER_SDRAM_SPAN 8388608
#define DMA_LCD_READ_MASTER_SDRAM_STARVATION_INDICATOR 0
#define DMA_LCD_READ_MASTER_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define DMA_LCD_READ_MASTER_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define DMA_LCD_READ_MASTER_SDRAM_T_AC 5.4
#define DMA_LCD_READ_MASTER_SDRAM_T_MRD 3
#define DMA_LCD_READ_MASTER_SDRAM_T_RCD 15.0
#define DMA_LCD_READ_MASTER_SDRAM_T_RFC 70.0
#define DMA_LCD_READ_MASTER_SDRAM_T_RP 15.0
#define DMA_LCD_READ_MASTER_SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by dma_LCD_write_master
 *
 */

#define DMA_LCD_WRITE_MASTER_SDRAM_BASE 0x800000
#define DMA_LCD_WRITE_MASTER_SDRAM_CAS_LATENCY 2
#define DMA_LCD_WRITE_MASTER_SDRAM_CONTENTS_INFO
#define DMA_LCD_WRITE_MASTER_SDRAM_INIT_NOP_DELAY 0.0
#define DMA_LCD_WRITE_MASTER_SDRAM_INIT_REFRESH_COMMANDS 2
#define DMA_LCD_WRITE_MASTER_SDRAM_IRQ -1
#define DMA_LCD_WRITE_MASTER_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_LCD_WRITE_MASTER_SDRAM_IS_INITIALIZED 1
#define DMA_LCD_WRITE_MASTER_SDRAM_NAME "/dev/sdram"
#define DMA_LCD_WRITE_MASTER_SDRAM_POWERUP_DELAY 100.0
#define DMA_LCD_WRITE_MASTER_SDRAM_REFRESH_PERIOD 15.625
#define DMA_LCD_WRITE_MASTER_SDRAM_REGISTER_DATA_IN 1
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_ADDR_WIDTH 0x16
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_BANK_WIDTH 2
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_COL_WIDTH 8
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_DATA_WIDTH 16
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_NUM_BANKS 4
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define DMA_LCD_WRITE_MASTER_SDRAM_SDRAM_ROW_WIDTH 12
#define DMA_LCD_WRITE_MASTER_SDRAM_SHARED_DATA 0
#define DMA_LCD_WRITE_MASTER_SDRAM_SIM_MODEL_BASE 0
#define DMA_LCD_WRITE_MASTER_SDRAM_SPAN 8388608
#define DMA_LCD_WRITE_MASTER_SDRAM_STARVATION_INDICATOR 0
#define DMA_LCD_WRITE_MASTER_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define DMA_LCD_WRITE_MASTER_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define DMA_LCD_WRITE_MASTER_SDRAM_T_AC 5.4
#define DMA_LCD_WRITE_MASTER_SDRAM_T_MRD 3
#define DMA_LCD_WRITE_MASTER_SDRAM_T_RCD 15.0
#define DMA_LCD_WRITE_MASTER_SDRAM_T_RFC 70.0
#define DMA_LCD_WRITE_MASTER_SDRAM_T_RP 15.0
#define DMA_LCD_WRITE_MASTER_SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by dma_read_master
 *
 */

#define DMA_READ_MASTER_SDRAM_BASE 0x800000
#define DMA_READ_MASTER_SDRAM_CAS_LATENCY 2
#define DMA_READ_MASTER_SDRAM_CONTENTS_INFO
#define DMA_READ_MASTER_SDRAM_INIT_NOP_DELAY 0.0
#define DMA_READ_MASTER_SDRAM_INIT_REFRESH_COMMANDS 2
#define DMA_READ_MASTER_SDRAM_IRQ -1
#define DMA_READ_MASTER_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_READ_MASTER_SDRAM_IS_INITIALIZED 1
#define DMA_READ_MASTER_SDRAM_NAME "/dev/sdram"
#define DMA_READ_MASTER_SDRAM_POWERUP_DELAY 100.0
#define DMA_READ_MASTER_SDRAM_REFRESH_PERIOD 15.625
#define DMA_READ_MASTER_SDRAM_REGISTER_DATA_IN 1
#define DMA_READ_MASTER_SDRAM_SDRAM_ADDR_WIDTH 0x16
#define DMA_READ_MASTER_SDRAM_SDRAM_BANK_WIDTH 2
#define DMA_READ_MASTER_SDRAM_SDRAM_COL_WIDTH 8
#define DMA_READ_MASTER_SDRAM_SDRAM_DATA_WIDTH 16
#define DMA_READ_MASTER_SDRAM_SDRAM_NUM_BANKS 4
#define DMA_READ_MASTER_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define DMA_READ_MASTER_SDRAM_SDRAM_ROW_WIDTH 12
#define DMA_READ_MASTER_SDRAM_SHARED_DATA 0
#define DMA_READ_MASTER_SDRAM_SIM_MODEL_BASE 0
#define DMA_READ_MASTER_SDRAM_SPAN 8388608
#define DMA_READ_MASTER_SDRAM_STARVATION_INDICATOR 0
#define DMA_READ_MASTER_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define DMA_READ_MASTER_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define DMA_READ_MASTER_SDRAM_T_AC 5.4
#define DMA_READ_MASTER_SDRAM_T_MRD 3
#define DMA_READ_MASTER_SDRAM_T_RCD 15.0
#define DMA_READ_MASTER_SDRAM_T_RFC 70.0
#define DMA_READ_MASTER_SDRAM_T_RP 15.0
#define DMA_READ_MASTER_SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by dma_write_master
 *
 */

#define DMA_WRITE_MASTER_SDRAM_BASE 0x800000
#define DMA_WRITE_MASTER_SDRAM_CAS_LATENCY 2
#define DMA_WRITE_MASTER_SDRAM_CONTENTS_INFO
#define DMA_WRITE_MASTER_SDRAM_INIT_NOP_DELAY 0.0
#define DMA_WRITE_MASTER_SDRAM_INIT_REFRESH_COMMANDS 2
#define DMA_WRITE_MASTER_SDRAM_IRQ -1
#define DMA_WRITE_MASTER_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_WRITE_MASTER_SDRAM_IS_INITIALIZED 1
#define DMA_WRITE_MASTER_SDRAM_NAME "/dev/sdram"
#define DMA_WRITE_MASTER_SDRAM_POWERUP_DELAY 100.0
#define DMA_WRITE_MASTER_SDRAM_REFRESH_PERIOD 15.625
#define DMA_WRITE_MASTER_SDRAM_REGISTER_DATA_IN 1
#define DMA_WRITE_MASTER_SDRAM_SDRAM_ADDR_WIDTH 0x16
#define DMA_WRITE_MASTER_SDRAM_SDRAM_BANK_WIDTH 2
#define DMA_WRITE_MASTER_SDRAM_SDRAM_COL_WIDTH 8
#define DMA_WRITE_MASTER_SDRAM_SDRAM_DATA_WIDTH 16
#define DMA_WRITE_MASTER_SDRAM_SDRAM_NUM_BANKS 4
#define DMA_WRITE_MASTER_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define DMA_WRITE_MASTER_SDRAM_SDRAM_ROW_WIDTH 12
#define DMA_WRITE_MASTER_SDRAM_SHARED_DATA 0
#define DMA_WRITE_MASTER_SDRAM_SIM_MODEL_BASE 0
#define DMA_WRITE_MASTER_SDRAM_SPAN 8388608
#define DMA_WRITE_MASTER_SDRAM_STARVATION_INDICATOR 0
#define DMA_WRITE_MASTER_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define DMA_WRITE_MASTER_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define DMA_WRITE_MASTER_SDRAM_T_AC 5.4
#define DMA_WRITE_MASTER_SDRAM_T_MRD 3
#define DMA_WRITE_MASTER_SDRAM_T_RCD 15.0
#define DMA_WRITE_MASTER_SDRAM_T_RFC 70.0
#define DMA_WRITE_MASTER_SDRAM_T_RP 15.0
#define DMA_WRITE_MASTER_SDRAM_T_WR 14.0


/*
 * serialflash configuration
 *
 */

#define ALT_MODULE_CLASS_serialflash BeMicro_Max10_serial_flash_controller
#define SERIALFLASH_BASE 0x2000
#define SERIALFLASH_IRQ 2
#define SERIALFLASH_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SERIALFLASH_NAME "/dev/serialflash"
#define SERIALFLASH_REGISTER_OFFSET 1024
#define SERIALFLASH_SPAN 2048
#define SERIALFLASH_TYPE "BeMicro_Max10_serial_flash_controller"


/*
 * sys_clk_timer configuration
 *
 */

#define ALT_MODULE_CLASS_sys_clk_timer altera_avalon_timer
#define SYS_CLK_TIMER_ALWAYS_RUN 0
#define SYS_CLK_TIMER_BASE 0x1020
#define SYS_CLK_TIMER_COUNTER_SIZE 32
#define SYS_CLK_TIMER_FIXED_PERIOD 0
#define SYS_CLK_TIMER_FREQ 50000000
#define SYS_CLK_TIMER_IRQ 1
#define SYS_CLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_CLK_TIMER_LOAD_VALUE 49999
#define SYS_CLK_TIMER_MULT 0.001
#define SYS_CLK_TIMER_NAME "/dev/sys_clk_timer"
#define SYS_CLK_TIMER_PERIOD 1
#define SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define SYS_CLK_TIMER_RESET_OUTPUT 0
#define SYS_CLK_TIMER_SNAPSHOT 1
#define SYS_CLK_TIMER_SPAN 32
#define SYS_CLK_TIMER_TICKS_PER_SEC 1000
#define SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYS_CLK_TIMER_TYPE "altera_avalon_timer"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0x1000
#define SYSID_ID 944587856
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1561594935
#define SYSID_TYPE "altera_avalon_sysid_qsys"

#endif /* __SYSTEM_H_ */
